#!/bin/bash

root=`dirname $0`

wget -O- ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz \
  | gzip -dc > hs38a.fa

[ ! -f hs38a.fa.alt ] && grep _alt $root/resource-GRCh38/hs38d6.fa.alt > hs38a.fa.alt
[ ! -f hs38a.fa.bwt ] && echo -e "\nPlease run 'bwa index hs38a.fa'...\n"
